services:
  postgres:
    image: 'postgres:latest'
    restart: always
    env_file:
      - './env/dev/postgres.env'
      - './env/dev/postgres-secrets.env'
    ports:
      - '8032:5432'
    healthcheck:
      test: 'pg_isready -U postgres'
      interval: 10s
      timeout: 5s
      retries: 3
    volumes:
      - './out/postgres_data:/var/lib/postgresql/data'
    networks:
      - template

  idb-template:
    build: .
    image: 'idb-template:latest'
    env_file:
      - './env/dev/idb-template-secrets.env'
      - './env/dev/idb-template.env'
    ports:
      - '8080:8080'
    depends_on:
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy
    healthcheck:
      test: 'wget --no-verbose --tries=1 --spider http://localhost:8080/actuator/health || exit 1'
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - template

networks:
  template:
    driver: bridge
