spring:
  profiles:
    active: dev

  application:
    name: auth-api

  main:
    web-application-type: reactive

  codec:
    max-in-memory-size: ${SPRING_CODEC_MAX_IN_MEMORY_SIZE}

  jackson:
    property-naming-strategy: ${SPRING_JACKSON_PROPERTY_NAMING_STRATEGY}

  # Cassandra configuration
  cassandra:
    keyspace-name: ${SPRING_CASSANDRA_KEYSPACE_NAME}
    contact-points: ${SPRING_CASSANDRA_CONTACT_POINTS}
    port: ${SPRING_CASSANDRA_PORT}
    username: ${SPRING_CASSANDRA_USER}
    password: ${SPRING_CASSANDRA_PASSWORD}
    local-datacenter: ${SPRING_CASSANDRA_LOCAL_DATACENTER}
    schema-action: ${SPRING_CASSANDRA_SCHEMA_ACTION}

  # Session configuration
  session:
    timeout: ${SPRING_SESSION_TIMEOUT}

  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST}
      port: ${SPRING_DATA_REDIS_PORT}
