spring:
  # Import configuration
  config:
    import: |
      optional:file:./env/dev/idb-auth.env[.properties],
      optional:file:./env/dev/idb-auth-secrets.env[.properties]

    activate:
      on-profile: dev
logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG


