spring:
  profiles:
    active: dev

  application:
    name: auth-api

  main:
    web-application-type: reactive

  # Cassandra configuration
  cassandra:
    keyspace-name: ${SPRING_CASSANDRA_KEYSPACE_NAME}
    contact-points: ${SPRING_CASSANDRA_CONTACT_POINTS}
    port: ${SPRING_CASSANDRA_PORT}
    username: ${SPRING_CASSANDRA_USER}
    password: ${SPRING_CASSANDRA_PASSWORD}
    local-datacenter: ${SPRING_CASSANDRA_LOCAL_DATACENTER}
    schema-action: ${SPRING_CASSANDRA_SCHEMA_ACTION}

  # Flyway configuration
  flyway:
    url: ${SPRING_FLYWAY_URL}
    user: ${SPRING_FLYWAY_USER}
    password: ${SPRING_FLYWAY_PASSWORD}

  mail:
    host: ${SPRING_MAIL_HOST}
    port: ${SPRING_MAIL_PORT}
    username: ${SPRING_MAIL_USERNAME}
    password: ${SPRING_MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: ${SPRING_MAIL_SMTP_AUTH}
          starttls:
            enable: ${SPRING_MAIL_SMTP_STARTTLS_ENABLE}
