services:
  redis:
    image: 'redis:latest'
    restart: always
    env_file:
      - './env/dev/redis.env'
      - './env/dev/redis-secrets.env'
    ports:
      - '3079:6379'
    healthcheck:
      test: 'redis-cli ping'
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - struct-api

  postgres:
    image: 'postgres:latest'
    restart: always
    env_file:
      - './env/dev/postgres.env'
      - './env/dev/postgres-secrets.env'
    ports:
      - '3032:5432'
    healthcheck:
      test: 'pg_isready -U postgres'
      interval: 10s
      timeout: 5s
      retries: 3
    volumes:
      - './out/postgres_data:/var/lib/postgresql/data'
    networks:
      - struct-api

  idb-struct-api:
    build: .
    image: 'idb-struct-api:latest'
    env_file:
      - './env/dev/idb-struct-secrets.env'
      - './env/dev/idb-struct.env'
    ports:
      - '3080:8080'
    depends_on:
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy
    healthcheck:
      test: 'wget --no-verbose --tries=1 --spider http://localhost:8080/actuator/health || exit 1'
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - struct-api

networks:
  struct-api:
    driver: bridge
