name: Build and Deploy the whole project

on:
  push:
    branches:
      - 'feature/**'
  pull_request:
    branches:
      - dev

jobs:
  lint-test:
    uses: ./.github/workflows/lint-test.yaml

  deploy-struct-api:
    needs: [lint-test]
    runs-on: ubuntu-latest
    if: contains(github.ref, 'feature/struct-api')
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK 21 alpine
        uses: actions/setup-java@v4
        with:
          distribution: 'alpine'
          java-version: '21'

      - name: Setup Gradle Wrapper
        uses: gradle/gradle-build-action@v3

      - name: Build app image
        run: |
          cd struct-api
          docker build -t struct-api .

      - name: Zipping the image
        run: |
          cd struct-api
          docker save struct-api:latest | gzip > struct-api.tar.gz

      - name: Deploy with SCP
        uses: appleboy/scp-action@v0.0.10
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "struct-api/struct-api.tar.gz"
          target: "$HOME/ci-cd/"
