name: Build and Deploy the whole project

on:
  push:
    branches:
      - 'feature/**'
  pull_request:
    branches:
      - dev

jobs:
  lint-test:
    uses: .github/workflows/lint-test.yaml

  setup-java:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '21'

  build-struct-api:
    needs: [lint-test, setup-java]
    runs-on: ubuntu-latest
    if: success() && contains(github.ref, 'feature/struct-api')
    steps:
      - name: Navigate to struct-api
        run: cd struct-api

      - name: Build struct-api
        run: ./gradlew build

  deploy:
    needs: [build-struct-api]
    runs-on: ubuntu-latest
    if: success()
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '21'

      - name: Deploy with SCP
        uses: appleboy/scp-action@v0.0.10
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "build/**/*.jar"
          target: "/home/${{ secrets.SSH_USERNAME }}/ssh_uploads/"
