name: Project Deployment

on:
  push:
    branches:
      - 'feature/**'
  pull_request:
    branches:
      - 'dev'

jobs:
  struct-api-deployment:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '21'

      - name: Set up Gradle
        uses: gradle/gradle-build-action@v3

      - name: Check with Gradle
        run: |
          cd struct-api
          ./gradlew check

      - name: Build docker image and zip it
        run: |
          cd struct-api
          docker build -t struct-api . && docker save struct-api > struct-api.tar

      - name: SCP to server
        uses: appleboy/scp-action@v0.0.10
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          source: "struct-api/struct-api.tar"
          target: "~/ci-cd/"
