name: Lint and Test the whole project using Gradle

on:
  push:
    branches:
    - 'feature/**'
  pull_request:
      branches:
      - dev

jobs:
  check-struct-api:
    runs-on: ubuntu-latest
    if: contains(github.ref, 'feature/struct-api')

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '21'

      - name: Change directory
        run: cd struct-api

      - name: List files
        run: ls -la

      - name: Run Gradle check (lint and test)
        run: ./gradlew check
