name: Lint and Test the whole project using Gradle

on:
    push:
        branches:
        - 'feature/**'
    pull_request:
        branches:
        - dev

jobs:
  lint-test-struct-api:
    runs-on: ubuntu-latest
    if: success() && contains(github.ref, 'feature/struct-api')
    steps:
      - name: Setup Java
        uses: ./.github/workflows/setup-java.yml
        with:
          java-version: '21'

      - name: Change to directory
        run: cd struct-api

      - name: Run Gradle Lint
        run: ./gradlew lint

      - name: Run Gradle Tests
        run: ./gradlew test