name: Check using Gradle

on:
  [workflow_call]

jobs:
  check-struct-api:
    runs-on: ubuntu-latest
    if: contains(github.ref, 'feature/struct-api')

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '21'

      - name: Change directory
        run: cd struct-api

      - name: Run Gradle check (lint and test)
        run: ./gradlew check
