name: Check using Gradle

on:
  [workflow_call]

jobs:
  check-struct-api:
    runs-on: ubuntu-latest
    if: contains(github.ref, 'feature/struct-api')

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK 21 alpine
        uses: actions/setup-java@v4
        with:
          distribution: 'alpine'
          java-version: '21'

      - name: Setup Gradle Wrapper
        uses: gradle/gradle-build-action@v3

      - name: Run Gradle check (lint and test)
        run: |
          cd struct-api
          ./gradlew check
