name: Setup Java environment

on:
  workflow_call:
    inputs:
      java-version:
        description: 'Java version to setup'
        required: true
        default: '21'

jobs:
  setup-java:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: ${{ inputs.java-version }}
