name: JDK 21 tests using Gradle

on:
    push:
        branches:
        - '*'
    pull_request:
        branches:
        - dev

jobs:
    lint:
      uses: ./lint.yaml
    integration:
        needs: lint
        if: success()
        runs-on: ubuntu-latest
        steps:
        - name: Run Gradle Tests
          run: ./gradlew test