name: Project verification (linting & testing)

on:
  [workflow_call]

jobs:
  struct-api-verification:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '21'

      - name: Check with Gradle
        run: |
          cd struct-api
          ./gradlew check

      - name: Finish verification
        run: echo "Verified (•‿•)"
